production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railsrumble_production
  username: root
  password: v8E*QLw5v$*e

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railsrumble_development
  username: root
  password: maglione
